diff: Phalcon\Mvc\Model\Manager > Phalcon\Mvc\Model\ManagerInterface(not implemented)

setCustomEventsManager
getCustomEventsManager
setModelSource
getModelSource
setModelSchema
getModelSchema
setConnectionService
setWriteConnectionService
setReadConnectionService
getWriteConnection
getReadConnection
getReadConnectionService
getWriteConnectionService
keepSnapshots
isKeepingSnapshots
useDynamicUpdate
isUsingDynamicUpdate
addHasManyThrough
getRelationByAlias
getRelationRecords
getReusableRecords
setReusableRecords
clearReusableObjects