diff: Phalcon\Db\DialectInterface > Phalcon\Db\Dialect(not implemented)

getColumnDefinition
addColumn
modifyColumn
dropColumn
addIndex
dropIndex
addPrimaryKey
dropPrimaryKey
addForeignKey
dropForeignKey
createTable
dropTable
createView
dropView
tableExists
viewExists
describeColumns
listTables
listViews
describeIndexes
describeReferences
tableOptions