diff: Phalcon\Dispatcher > Phalcon\DispatcherInterface(not implemented)

__construct
setModuleName
getModuleName
setNamespaceName
getNamespaceName
getDefaultNamespace
getActiveMethod
setReturnedValue
wasForwarded